# Generated by Django 5.2.5 on 2025-08-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_homevideo'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_products', to='products.product')),
            ],
        ),
    ]
