# Generated by Django 5.2.5 on 2025-08-27 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_featuredproduct'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTheLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Shop the Look', max_length=200)),
                ('player_image', models.ImageField(upload_to='shop_look/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.PositiveIntegerField()),
                ('left', models.PositiveIntegerField(blank=True, null=True)),
                ('right', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='products.product')),
                ('shop_the_look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='homepage.shopthelook')),
            ],
        ),
    ]
