# Generated by Django 5.2.5 on 2025-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_person_name',
            field=models.TextField(default='Anonymous'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_person_number',
            field=models.TextField(default=1234567890),
            preserve_default=False,
        ),
    ]
